### ISSUE TITLE
Redactor: Default config update

### ISSUE THREAD

**Issue by WeArePercipio** [percipioglobal/craft#18]
Proposing the following default redactor config at `/cms/redactor/Content.json` to give more control and feedback to content editors.

```{
  "buttons": [
    "formatting",
    "bold",
    "italic",
    "lists",
    "sup",
    "sub",
    "link",
    "table",
    "html"
  ],
  "formatting": ["p", "h2", "h3", "h4"],
  "plugins": ["counter", "table"],
  "formattingAdd": {
    "span": {
      "title": "Highlight",
      "api": "module.inline.format",
      "args": {
        "tag": "span",
        "class": "text-teal-400"
      }
    }
  },
  "pastePlainText": true,
  "pasteImages": false,
  "pasteKeepStyle": ["p"],
  "spellcheck": true,
  "structure": true,
  "source": true,
  "toolbarFixed": true
}
```

**Comment by michtio** [comment]
The only one I would leave out is `html` tho. Also I would steer clear of the h2 in there, since we use h1 / h2 for the section titles, and then we still have h3/h4/h5/h6 left @WeArePercipio

**Comment by WeArePercipio** [comment]
yeah agree on the H2 omission.... 

I use the HTML all the time content debugging for clients... is there a way to only add it for certain user groups?

**Comment by michtio** [comment]
I will look into that @WeArePercipio , but as far as I know not

What are the issues happening? I assume c/p from word / google sheets etc ... ?
You can configure the redactor that it strips out those kind of styles.
