### ISSUE TITLE
Tailwind config colors can be updated

### ISSUE THREAD

**Issue by davmcgregor** [percipioglobal/craft#44]
## Isssue

The colors in the [Tailwind config file](https://github.com/percipioglobal/craft/blob/develop/docker-config/webpack-dev-
craft/tailwind.config.js) reflect an older Tailwind version 

## Solution

The latest colors can be found in [Harding]((https://github.com/percipioglobal/harding-financial-app/blob/staging/tailwind.config.js) or NTP

**Comment by michtio** [comment]
@davmcgregor this will be closed as a non-issue :)
