### ISSUE TITLE
Organisms: FAQ finetune according to the NTP

### ISSUE THREAD

**Issue by WeArePercipio** [percipioglobal/craft#8]
FAQ content block required for content builder matrix

- Accordion [boolean] // allows the user to optionally enable a collapsable accordion style for the FAQ's - if disabled, questions are simply laid out `H3` [question] -> `<p>` [answer] with maybe a small `<hr>` separator 

Then a superTable loop [add new question]
- Question [plainText]
- Answer [redactor (simple)]

**Comment by michtio** [comment]
@WeArePercipio I'm not sure about the "accordeon" boolean to be fair. It sure is a nice to have, but I also feel it's a little contradictory with having a "styleguide" and "consistency" once a FAQ is used, in my opinion it should always look the same, just to improve UX according to the Law of Similarity or Gestalt's Principles: https://lawsofux.com/law-of-similarity.html
